-------------
---- WEB ----
-------------

CREATE STREAM MOVEMENTS (PERSON VARCHAR KEY, LOCATION VARCHAR)
  WITH (VALUE_FORMAT='JSON', PARTITIONS=1, KAFKA_TOPIC='movements');
  
INSERT INTO MOVEMENTS VALUES ('John', 'Lisbon');
INSERT INTO MOVEMENTS VALUES ('Ann', 'Sintra');
INSERT INTO MOVEMENTS VALUES ('Peter', 'São Paulo');
INSERT INTO MOVEMENTS VALUES ('Sophie', 'Fortaleza');


-------------
---- CLI ----
-------------

SHOW streams;

INSERT INTO MOVEMENTS VALUES ('John', 'Lisbon');
INSERT INTO MOVEMENTS VALUES ('Ann', 'Sintra');
INSERT INTO MOVEMENTS VALUES ('Peter', 'São Paulo');

SET 'auto.offset.reset' = 'earliest';

SELECT * FROM MOVEMENTS EMIT CHANGES;

CREATE TABLE PERSON_STATS WITH (VALUE_FORMAT='AVRO') AS
  SELECT PERSON,
    LATEST_BY_OFFSET(LOCATION) AS LATEST_LOCATION,
    COUNT(*) AS LOCATION_CHANGES,
    COUNT_DISTINCT(LOCATION) AS UNIQUE_LOCATIONS
  FROM MOVEMENTS
GROUP BY PERSON
EMIT CHANGES;

SHOW tables;
